### ISSUE TITLE
smie learnings?

### ISSUE THREAD

**Issue by jasonm23** [DamienCassou/nix-mode#1]
Nix mode has a nice use of SMIE, would you consider posting some notes on how you used it?

If you're too busy, I understand completely of course.

**Comment by DamienCassou** [comment]
I don't use this code as it is incomplete and doesn't work. I never managed to make it work because SMIE was (and maybe is still) under-documented.

**Comment by jasonm23** [comment]
Thanks for letting me know,  the level of documentation on SMIE (or lack of it) is what prompted me to ask you for notes.

Thanks anyway.
